### PR TITLE
Parse Garmin workout notes

### PR DESCRIPTION
**Pull request by PabiGamito**

### CODE REVIEW

**Comment by igoramadas** [comment]
Hi @PabiGamito , are the workout notes added before the activity is saved on Garmin?

**Comment by PabiGamito** [comment]
In certain cases, and the case I'm interested in I think so. I pulled the fit file from Garmin right after the activity was synced; I didn't edit the activity at all and it had notes from the workout. This was a workout generated as a Garmin daily suggested workout — it was a sprint intervals workout and it had the following notes: "8x0:10@2:35/km".

In any case, would probably be good to properly confirm that this data is available at the time the fit file is processed in the pipeline. Any chance you might be able to suggest a quick and easy way to check this?

**Comment by igoramadas** [comment]
Could you send me the original FIT file so I can double check? I need to run the parser with log activated to figure out where the notes are stored. It's binary data, and at the moment I don't have any pointers to the workout notes on the FIT descriptors (you can see the current fields for workouts [here](https://github.com/strautomator/core/blob/master/src/fitparser/fit.ts#L460)).

**Comment by PabiGamito** [comment]
Just tried parsing my fit file using `FitParser`'s `parse` function and it seems to be able to extract the workout notes as expected.

**Pull request merged**
